import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  PlayerError,
  rankCandidates,
  scoreCandidate,
  searchYouTube,
  type VideoMatch,
} from '../../src/services/player/youtubeSearch'

/**
 * Picking the video that is actually the requested song.
 *
 * This matters more than most ranking code, because the consequence of getting
 * it wrong is audible to a room full of people. A karaoke backing track, a
 * sped-up edit or someone's acoustic cover are all plausible search hits for a
 * pop single, and the DJ finds out at the worst possible moment.
 *
 * The other half is telling failures apart. Quota exhaustion and a bad key both
 * arrive as HTTP 403 and mean opposite things — "wait until tomorrow" versus
 * "fix what you pasted" — and a DJ mid-party cannot afford to guess.
 */

const song = { title: 'Levitating', artist: 'Dua Lipa' }

function candidate(
  videoTitle: string,
  channelTitle: string,
  videoId = 'v1',
): VideoMatch {
  return { videoId, videoTitle, channelTitle }
}

describe('choosing between videos', () => {
  it('prefers the label’s audio-only upload over the music video', () => {
    /**
     * "– Topic" channels are generated by YouTube from what the label
     * delivers: the album master, no intro, no outro, no channel bumper
     * talking over the first bar. It is the closest thing to a streaming
     * service's copy, which is what a party wants.
     */
    const topic = candidate('Levitating', 'Dua Lipa - Topic', 'topic')
    const video = candidate(
      'Dua Lipa - Levitating (Official Music Video)',
      'Dua Lipa',
      'video',
    )

    expect(rankCandidates([video, topic], song)[0]?.videoId).toBe('topic')
  })

  it('rejects the versions that are not the record', () => {
    const real = candidate('Levitating', 'Dua Lipa - Topic', 'real')
    const wrong = [
      candidate('Levitating (Live at Glastonbury)', 'Dua Lipa', 'live'),
      candidate('Levitating - Acoustic Cover', 'Some Guy', 'cover'),
      candidate('Levitating KARAOKE Instrumental', 'Sing Along', 'karaoke'),
      candidate('Levitating (sped up)', 'Edits Daily', 'sped'),
    ]

    const ranked = rankCandidates([...wrong, real], song)
    expect(ranked[0]?.videoId).toBe('real')
    // Not merely last — those versions must score below a plain result.
    for (const bad of wrong) {
      expect(scoreCandidate(bad, song)).toBeLessThan(scoreCandidate(real, song))
    }
  })

  /**
   * The penalty is for a *mismatch*, not for the word. Someone who asks for the
   * live version should get the live version, or the feature is just wrong in a
   * different direction.
   */
  it('allows a version the guest actually asked for', () => {
    const live = candidate('Levitating (Live at Glastonbury)', 'Dua Lipa')
    const studio = candidate('Levitating', 'Dua Lipa - Topic')
    const askedForLive = { title: 'Levitating (Live)', artist: 'Dua Lipa' }

    expect(scoreCandidate(live, askedForLive)).toBeGreaterThan(
      scoreCandidate(live, song),
    )
    // And the studio cut is still fine for someone who asked for it plainly.
    expect(rankCandidates([live, studio], song)[0]?.videoTitle).toBe(
      'Levitating',
    )
  })

  it('prefers a result that names the right artist', () => {
    const right = candidate('Levitating - Dua Lipa', 'Music Uploads')
    const wrong = candidate('Levitating - Someone Else', 'Music Uploads')

    expect(scoreCandidate(right, song)).toBeGreaterThan(
      scoreCandidate(wrong, song),
    )
  })

  it('keeps YouTube’s own order when nothing separates two results', () => {
    const first = candidate('Levitating', 'Dua Lipa - Topic', 'first')
    const second = candidate('Levitating', 'Dua Lipa - Topic', 'second')

    expect(rankCandidates([first, second], song).map((c) => c.videoId)).toEqual([
      'first',
      'second',
    ])
  })
})

describe('asking YouTube', () => {
  const fetchMock = vi.fn()

  beforeEach(() => {
    vi.stubGlobal('fetch', fetchMock)
    fetchMock.mockReset()
  })

  afterEach(() => {
    vi.unstubAllGlobals()
  })

  function respond(body: unknown, status = 200) {
    fetchMock.mockResolvedValue({
      ok: status >= 200 && status < 300,
      status,
      json: async () => body,
    })
  }

  it('only ever asks for videos that can be embedded', async () => {
    /**
     * Load-bearing rather than tidy: labels routinely forbid embedding, and a
     * blocked video fails *inside* the player as a grey box, with the song
     * already announced to the room as playing. Filtering at the source means
     * the failure cannot happen.
     */
    respond({
      items: [
        { id: { videoId: 'a' }, snippet: { title: 'Levitating', channelTitle: 'Dua Lipa - Topic' } },
      ],
    })

    await searchYouTube(song, 'test-key')

    const url = new URL(fetchMock.mock.calls[0]![0] as string)
    expect(url.searchParams.get('videoEmbeddable')).toBe('true')
    expect(url.searchParams.get('type')).toBe('video')
    expect(url.searchParams.get('q')).toBe('Levitating Dua Lipa')
    expect(url.searchParams.get('key')).toBe('test-key')
  })

  it('spends exactly one lookup per song', async () => {
    // The whole budget is ~100 of these a day. A retry or a confirming call
    // would halve that, so there must be exactly one request.
    respond({
      items: [
        { id: { videoId: 'a' }, snippet: { title: 'Levitating', channelTitle: 'Dua Lipa - Topic' } },
      ],
    })

    await searchYouTube(song, 'test-key')
    expect(fetchMock).toHaveBeenCalledTimes(1)
  })

  it('returns every candidate, not just the winner', async () => {
    // The alternatives are what make "wrong song" free later on.
    respond({
      items: [
        { id: { videoId: 'a' }, snippet: { title: 'Levitating', channelTitle: 'Dua Lipa - Topic' } },
        { id: { videoId: 'b' }, snippet: { title: 'Levitating', channelTitle: 'Dua Lipa' } },
      ],
    })

    expect(await searchYouTube(song, 'test-key')).toHaveLength(2)
  })

  it('tells a spent quota apart from a bad key', async () => {
    respond(
      { error: { errors: [{ reason: 'quotaExceeded' }] } },
      403,
    )
    await expect(searchYouTube(song, 'k')).rejects.toMatchObject({
      failure: 'quota',
    })

    respond({ error: { errors: [{ reason: 'badRequest' }] } }, 403)
    await expect(searchYouTube(song, 'k')).rejects.toMatchObject({
      failure: 'key_rejected',
    })
  })

  it('refuses to spend a request when there is no key', async () => {
    await expect(searchYouTube(song, '  ')).rejects.toBeInstanceOf(PlayerError)
    expect(fetchMock).not.toHaveBeenCalled()
  })

  it('reports an empty result as not found rather than crashing', async () => {
    respond({ items: [] })
    await expect(searchYouTube(song, 'k')).rejects.toMatchObject({
      failure: 'not_found',
    })
  })

  it('survives a response that is not JSON at all', async () => {
    fetchMock.mockResolvedValue({
      ok: false,
      status: 500,
      json: async () => {
        throw new Error('not json')
      },
    })
    await expect(searchYouTube(song, 'k')).rejects.toMatchObject({
      failure: 'network',
    })
  })
})
